// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6s7NATYGbdLyVlZbtVjsyG1ssQ2wgyjs',
    appId: '1:870276183804:web:1c822ebc88c03d23a50979',
    messagingSenderId: '870276183804',
    projectId: 'teaching-flutter-crud',
    authDomain: 'teaching-flutter-crud.firebaseapp.com',
    storageBucket: 'teaching-flutter-crud.firebasestorage.app',
    measurementId: 'G-LPVMW1SX58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0zsFJcKNz4lQaA2nDx5e9yunPo9KRy7w',
    appId: '1:870276183804:android:c7d63b63a2942a6aa50979',
    messagingSenderId: '870276183804',
    projectId: 'teaching-flutter-crud',
    storageBucket: 'teaching-flutter-crud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWkiqTxinOccTEzEm0XCn4rt83EjEVQmQ',
    appId: '1:870276183804:ios:1049eb0ce678e39da50979',
    messagingSenderId: '870276183804',
    projectId: 'teaching-flutter-crud',
    storageBucket: 'teaching-flutter-crud.firebasestorage.app',
    iosBundleId: 'com.example.teachingFlutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWkiqTxinOccTEzEm0XCn4rt83EjEVQmQ',
    appId: '1:870276183804:ios:1049eb0ce678e39da50979',
    messagingSenderId: '870276183804',
    projectId: 'teaching-flutter-crud',
    storageBucket: 'teaching-flutter-crud.firebasestorage.app',
    iosBundleId: 'com.example.teachingFlutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6s7NATYGbdLyVlZbtVjsyG1ssQ2wgyjs',
    appId: '1:870276183804:web:9cf772cf69c9725da50979',
    messagingSenderId: '870276183804',
    projectId: 'teaching-flutter-crud',
    authDomain: 'teaching-flutter-crud.firebaseapp.com',
    storageBucket: 'teaching-flutter-crud.firebasestorage.app',
    measurementId: 'G-BHZWXV8FXN',
  );
}
